create database smarteditor;

use smarteditor;

CREATE TABLE `BOARD` (
	`BOARD_SEQ`	INT(11)	NOT NULL	COMMENT '게시글 일련번호(PK)',
	`CONTENT`	VARCHAR(3000)	NOT NULL	COMMENT '내용',
	`INSERT_TIME`	DATETIME	NOT NULL	COMMENT '등록날짜',
	`UPDATE_TIME`	DATETIME	NULL	COMMENT '수정날짜',
	`DELETE_TIME`	DATETIME	NULL	COMMENT '삭제날짜',
	`DELETE_YN`	ENUM('Y', 'N')	NOT NULL	DEFAULT 'N'	COMMENT '삭제여부'
);

CREATE TABLE `IMG` (
	`IMG_SEQ`	INT(11)	NOT NULL	COMMENT '이미지 일련번호(PK)',
	`BOARD_SEQ`	INT(11)	NOT NULL	COMMENT '게시글 일련번호',
	`ORIGINAL_IMG_NAME`	VARCHAR(500)	NOT NULL	COMMENT '원본 이미지이름',
	`SAVE_IMG_NAME`	VARCHAR(3000)	NOT NULL	COMMENT '저장 이미지이름',
	`IMG_SIZE`	INT(11)	NOT NULL	COMMENT '이미지크기',
	`INSERT_TIME`	DATETIME	NOT NULL	COMMENT '등록날짜',
	`DELETE_TIME`	DATETIME	NULL	COMMENT '삭제날짜',
	`DELETE_YN`	ENUM('Y', 'N')	NOT NULL	DEFAULT 'N'	COMMENT '삭제여부'
);

ALTER TABLE `BOARD` ADD CONSTRAINT `PK_BOARD` PRIMARY KEY (
	`BOARD_SEQ`
);

ALTER TABLE `IMG` ADD CONSTRAINT `PK_IMG` PRIMARY KEY (
	`IMG_SEQ`
);

select * from img;